a=(10,20,25.23,"kumar",'aadarsh')
print(a)
print(type(a))
print("accessing tuple element from 0th to 4th potion")
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print("accessing tuple element from simple reverse method")
print(a[-1])
print(a[-2])
print(a[-3])
print(a[-4])
print(a[-5])