(lambda x:print("add immideately invoked function           =",x+5))(12)
print()
(lambda x:print("sub immideately invoked function           =",x-5))(12)
print()
(lambda x:print("multiply immideately invoked function      =",x*5))(25)
print()
(lambda x:print("devide immideately invoked function        =",x/5))(38)
print()
(lambda x:print("quotient immideately invoked function      =",x//5))(14)
print()
(lambda x:print("remender immideately invoked function      =",x%5))(14)
print()
(lambda x:print("squre immideately invoked function         =",x**5))(10)
print()