(lambda x,y:print("add immideately invoked function           =",x+y))(12,5)
print()
(lambda x,y:print("sub immideately invoked function           =",x-y))(12,5)
print()
(lambda x,y:print("multiply immideately invoked function      =",x*y))(25,5)
print()
(lambda x,y:print("devide immideately invoked function        =",x/y))(38,5)
print()
(lambda x,y:print("quotient immideately invoked function      =",x//y))(14,5)
print()
(lambda x,y:print("remender immideately invoked function      =",x%y))(14,5)
print()
(lambda x,y:print("squre immideately invoked function         =",x**y))(10,5)
print()