a=[10,20,30]
print(a)
print(type(a))
new_a=tuple(a)
print(new_a)
print(type(new_a))
print('***************')
b={10,20,30}
print(b)
print(type(b))
new_b=tuple(b)
print(new_b)
print(type(new_b))
print('***************')
c={10:'kuamr',20:'aadarsh',30:'lovely boy'}
print(c)
print(type(c))
new_c=tuple(c)
print(new_c)
print(type(new_c))
print('***************')
d='kumar aadarsh lovely boy badshah'
print(d)
print(type(d))
new_d=tuple(d)
print(new_d)
print(type(new_d))