a=input("your name:")
b=int(input("your mobile number:"))
c=input("your class:")
d=int(input("your roll no:"))
print('Your name is ',a)
print('Your mobile number ',b)
print('Your class is ',c)
print('Your roll no is ',d)
print(type(b))