#range function 1
a=range(5)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print("rest of thecode")
#range function 2
a=range(2,20,2)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print(a[5])
print(a[6])
print(a[7])
print(a[8])
print("rest of thecode")
#reverse range function
a=range(10,1,-2)
print(a[0])
print(a[1])
print(a[2])
print(a[3])
print(a[4])
print("rest of thecode")