#checking method for readmode:
f=open("myfile1.txt",mode="r",encoding='utf-8')
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
print()
#checking method for writemode:
f=open("myfile1.txt",mode="w",encoding='utf-8')
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
print()
#checking method for appending:
f=open("myfile1.txt",mode="a",encoding='utf-8')
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
print()
#cheking method for "x" mode in file handling
f=open("lovly_boy.txt",mode="x",encoding='utf-8')
#it will create a file the file is exists it will shows error
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
#checking method for readmode:
f=open("myfile1.txt",mode="r+",encoding='utf-8')
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
print()
#checking method for writemode:
f=open("myfile1.txt",mode="w+",encoding='utf-8')
print('FILE NAME =',f.name)
print('FILE MODE =',f.mode)
print('FILE IS READABLE =',f.readable())
print('FILE IS WRITEABLE =',f.writable())
print('FILE IS CLOSED =',f.closed)
f.close()
print('FILE IS CLOSED =',f.closed)
print()