file_name=input('enter your file name=')
file=open(file_name, mode='r')
print(file.tell())
file.seek(7)
print(file.tell())
data1=file.read()
print(data1)
file.seek(2)
print(file.tell())
data2=file.read()
print(data2)